[package]
name = "haproxy-geoip2-module"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
haproxy-api = { version = "0.8" }
haproxy-geoip2 = { path = ".." }
mlua = "0.9"
